spring:
  application:
    name: newsletter
  profiles:
    active: prod
  config:
    import: optional:configserver:http://localhost:8888
  data:
    mongodb:
      port: 27017
      host: localhost
      database: newsletter
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# Configuracao da porta do serviço de forma aleatoria
server:
  port: ${PORT:0}

firebase:
  credential-file-name: firebase-account.json
  recipient-token: eQc0lsqCGoOBXxW95_k8Pr:APA91bEAa8vtT8Yqn6V2UOFOGyEa7anf0UxSi7DnaJXpg8nxBesUeEwGLDcc5pyP59R3-LkUWPAvAz8vAgaJAA60_Bgm_pjrDHzDQ-A2gg6jdT2Ak-9rPyX5X3K5XqG9L9TxZsC6yXi-

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

newslatter:
  rabbitmq:
    exchange: newslatter.exchange
    rountingkey: newslatter.logs.rountingkey
    queue: newslatter.logs.queue

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG